[package]
name = "RubyLLM"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
tokenizers = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"